# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildanddeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v1
        with:
         java-version: '11.0.1'
         java-package: jdk
         architecture: x64

      - uses:  vijaySamanuri/hyscale-action@v4
        id: install-hyscale
        with:
          hyscale-version: 0.9.8.1.195
          
      - uses:  vijaySamanuri/hyscale-deploy@v1
        id: deploy-hyscale
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: deploy service -f helloworld-go.hspec -a helloworld-go -n helloworld-go
        
